<table id='admin_urls' cellspacing=0>
    <thead>
        <tr>
            <th>URL</th>
            <th>Частота проверки</th>
            <th>Количество повторов</th>
            <th>Дата создания</th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<script>

    function getUrls() {
        $.ajax({
            url: '/admin/getUrls',
            type: "post",
            dataType: 'JSON',
            success: function (data) {
            $("#admin_urls tbody").empty();
            for(var i = 0; i < data.length; i++) {
                $("#admin_urls tbody").append("<tr><td>" + 
                data[i].url +"</td><td>" + data[i].freq + " сек</td><td>" + 
                data[i].repeats + "</td><td>" + data[i].datetime +
                "</td><td><a href='/admin/url/" + data[i].url_id + 
                "'>Подробнее</a></td></tr>");
            }
            },
            error: function (data) {
                alert("Произошла неизвестная ошибка");
            }
        });
    }

    getUrls();

    setInterval(getUrls, 3000);

</script>