<h1><?php echo $url -> url;?></h1>
<table id='admin_check_info' cellspacing=0>
    <thead>
        <tr>
            <th>Дата проверки</th>
            <th>http-код</th>
            <th>Номер попытки</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<a href="/admin">Назад</a>
<script>
    function getCheck() {
        $.ajax({
            url: '/admin/getCheckInfo/<?php echo $url -> url_id?>',
            type: "post",
            dataType: 'JSON',
            success: function (data) {
                $("#admin_check_info tbody").empty();
                if(data === null) {
                    return;
                }
                if(data.result == false) {
                    alert(data.message);
                }
                for(var i = 0; i < data.length; i++) {
                    $("#admin_check_info tbody").append("<tr><td>" + 
                    data[i].datetime +"</td><td>" + data[i].http + "</td><td>" + 
                    data[i].try_no + "</td></tr>");
                }
            },
            error: function (data) {
                alert("Произошла неизвестная ошибка");
            }
        });
    }

    getCheck();

    setInterval(getCheck, 10000);

</script>