<form action="/addUrl" method="post" id='addUrlForm'>
    <div id='form'>
        <div>
            <label for="url">url для проверки</label>
            <input id='url' required type="url">
        </div>
        <div>
        </div>
        <div>
            <label for="freq">Частота проверки</label>
            <select id='freq'>
                <option selected value="1">1 мин</option>
                <option value="5">5 мин</option>
                <option value="10">10 мин</option>
            </select>
        </div>
        <div>
            <label for="repeats">Количество повторов в случае ошибки</label>
            <input id='repeats' required type="number" value='0' min='0' max='10'>
        </div>
    </div>
    <button type="submit">Добавить</button>
</form>
<br>
<a href='/admin'>Админ</a>